// Content below is autogenerated by ojster template engine
// usually there is no reason to edit it manually
goog.provide('jb.ui.ComboboxTemplate');

goog.require('ojster.Template');

/**
 * @param {Object=} opt_data
 * @param {Object=} opt_ctx
 * @param {ojster.StringWriter=} opt_writer
 * @constructor
 * @extends {ojster.Template}
 */
jb.ui.ComboboxTemplate = function (opt_data, opt_ctx, opt_writer) {
	goog.base(this, opt_data, opt_ctx, opt_writer);
};
goog.inherits(jb.ui.ComboboxTemplate, ojster.Template);

jb.ui.ComboboxTemplate.prototype.renderBlockMain = function () { // @6:1
	var self = this;
	var d = this.data, vars = this.vars;
	self.writer.write(
		'<div class="',
		self.baseCssName, // @7:17
		'"><input type="text" class="',
		goog.getCssName(/** @type {string} */ (self.baseCssName), 'input'), // @8:33
		'" placeholder="',
		self.escape(d.caption), // @8:65
		'"><span class="',
		goog.getCssName(/** @type {string} */ (self.baseCssName), 'arrow'), // @9:20
		'">▼</span></div>'
	);
}; // @11:1

